
One exception class is used.  The class is called 'Failure'
and is derived from std::exception.
